### ISSUE TITLE
Options get highlighted as green

### ISSUE THREAD

**Issue by davidcelis** [davidcelis/language-fish-shell#1]
This is just an aesthetic nitpick, but I'd rather that short and long didn't get highlighted as green like Strings. Try to figure out how to prevent them from, preferably, being highlighted at all.

**Comment by bucaran** [comment]
Agree. I would rather have them in an entirely different color. What do you think?

**Comment by davidcelis** [comment]
I still think that options should just look like regular text as most syntax themes for shells that I know of are like this. To be honest, I simply ported this over from a TextMate theme for personal use and I've never taken the time to learn the nuances of changing how things are highlighted. I would be extremely happy to accept patches from people, though :sweat:

**Comment by bucaran** [comment]
Let me see what I can do. I still need to get around reading that TextMate tmBundle tutorial post.

**Comment by davidcelis** [comment]
Great! Please reach out if I can be of any help. I'd love to do what I can even though my experience is limited!

**Comment by bucaran** [comment]
Thanks. _Will do_!
