### ISSUE TITLE
Incorrect handling of escaped characters

### ISSUE THREAD

**Issue by RSully** [davidcelis/language-fish-shell#8]
Something like this breaks the highlighting:

```
set -l datafile (eval echo \"$data\")
```

![screen shot 2016-07-03 at 19 06 03](https://cloud.githubusercontent.com/assets/185004/16548094/39b1f2c0-4151-11e6-978a-afad0e8dcc89.png)

**Comment by brj** [comment]
Yes, so in the meantime, do

``
set -l datafile (eval echo "\"$data\"")
```

**Comment by RSully** [comment]
I originally tried your second example, and it has different output. Your first example does work though:

```
> set data '$var/thing'
> eval echo \"$data\"
/thing
> eval echo '"$data"'
$var/thing
> eval echo "\"$data\""
/thing
```

However, obviously I am not going to change my code just for syntax highlighting ;). I'll take a look at the source here and see how difficult it may be to fix.

Also, it appears whatever syntax highlighter GitHub uses for fish also has this same problem. I'm guessing they're both based on the same codebase.

**Comment by brj** [comment]
You are right, the second example is bad.

> I'm guessing they're both based on the same codebase.

Yeah, I think so too.
